
DROP TABLE IF EXISTS M_USER;

CREATE TABLE M_USER (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    fullname VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    username VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    role VARCHAR(255),
    address VARCHAR(255),
    image BLOB,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR(50),
    MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    IS_DELETED BOOLEAN DEFAULT FALSE NOT NULL
);



--THIS is for postgres, but H2 does not support unique constraint with condition

--CREATE UNIQUE INDEX unique_email_not_deleted
--ON M_USER (email)
--WHERE is_deleted = FALSE;

